
'use server';
/**
 * @fileOverview A conversational AI farmer assistant.
 *
 * - aiFarmer - A function that handles the conversation with the AI farmer.
 * - AIFarmerInput - The input type for the aiFarmer function.
 * - AIFarmerOutput - The return type for the aiFarmer function.
 */

import {z} from 'zod';
import { languageEnum } from '@/lib/schemas';


const chatMessageSchema = z.object({
  role: z.enum(['user', 'model']),
  content: z.string(),
});

const AIFarmerInputSchema = z.object({
  history: z.array(chatMessageSchema).describe('The conversation history.'),
  language: languageEnum,
});
export type AIFarmerInput = z.infer<typeof AIFarmerInputSchema>;

const AIFarmerOutputSchema = z.object({
  response: z.string().describe('The AI farmer\'s response.'),
});
export type AIFarmerOutput = z.infer<typeof AIFarmerOutputSchema>;


export async function aiFarmer(
  input: AIFarmerInput
): Promise<AIFarmerOutput> {
  const userMessage = input.history[input.history.length - 1]?.content.toLowerCase() || '';

  let response = '';

  if (userMessage.includes('summer') && userMessage.includes('crop')) {
    response = 'Simulated Answer: In summer, heat-tolerant crops like corn, tomatoes, and peppers thrive. Ensure consistent watering. Your custom model would provide region-specific advice.';
  } else if (userMessage.includes('soil health')) {
    response = 'Simulated Answer: To improve soil health, consider adding compost, using cover crops between seasons, and practicing crop rotation. Your custom model would give more detailed recommendations based on your soil type.';
  } else if (userMessage.includes('pest') && (userMessage.includes('tomato') || userMessage.includes('tomatoes'))) {
    response = 'Simulated Answer: A common pest for tomatoes is the Hornworm. They are large green caterpillars that can eat leaves and fruit. Hand-picking them off the plants is an effective organic control method. This is a simulated response.';
  } else if (userMessage.includes('tomato') && (userMessage.includes('seed') || userMessage.includes('harvest'))) {
    response = 'Simulated Answer: Tomato seeds typically germinate in 5-10 days. From planting, it can take anywhere from 60 to over 80 days to harvest the first fruits, depending on the variety (e.g., Early Girl vs. Beefsteak). This is a simulated response.';
  } else {
    // General agriculture check
    const agricultureKeywords = [
        'farm', 'crop', 'soil', 'plant', 'harvest', 'pesticide', 'fertilizer',
        'irrigation', 'weather', 'seed', 'tractor', 'livestock', 'agriculture',
        'disease', 'pest'
    ];
    const isAgricultureRelated = agricultureKeywords.some(keyword => userMessage.includes(keyword));

    if (isAgricultureRelated) {
        response = `This is a simulated answer about "${input.history[input.history.length - 1]?.content}". In a real application, my response would be generated by your custom model to provide detailed information on this agricultural topic.`;
    } else {
        response = "I am an AI Farmer assistant. My expertise is limited to agriculture. Please ask me questions about topics like crops, soil health, pest control, or farming techniques.";
    }
  }


  // Simulate a small delay to make it feel more like a real API call
  await new Promise(resolve => setTimeout(resolve, 500));

  return {
    response: response,
  };
}
